POST http://localhost:31233/api/find
content-type: application/json

{
  "requestType"    : "find",
  "match"          : "dave",
  "type"           : ["airport"], 
  "where"          : ["United States"],
  "limit"          : 10
}