POST http://localhost:8000/api/find
content-type: application/json

{
  "requestType"    : "find",
  "match"          : "aqua",
  "type"           : ["airport"], 
  "where"          : ["world"],
  "limit"          : 15
}