POST http://localhost:31380/api/find
content-type: application/json

{
  "requestType"    : "find",
  "match"          : "denver",
  "type"           : ["airport"], 
  "where"          : ["world"],
  "limit"          : 10
}