POST http://localhost:8000/api/distances

{
  "requestType"    : "distances",
   "places"         : [{"name":"place1", "latitude":  "40.6",  "longitude": "-105.1"},
                      {"name": "place2", "latitude":  "-33.9", "longitude": "151.2"},
                      {"name":"place3", "latitude":  "50",  "longitude": "-10.1"},
                      {"name": "place4", "latitude":  "60", "longitude": "11.2"}],
  "earthRadius"    : 6371
}