POST http://localhost:8000/api/distances

{
  "requestType"    : "distances",
   "places"         : [{"name": "place2", "latitude":  "-33.9", "longitude": "151.2"},
                      {"name": "place2", "latitude":  "-33.9", "longitude": "151.2"}],
  "earthRadius"    : 6371
}