POST http://localhost:8000/api/distances

{
  "requestType"    : "distances",
  "places"         : [{"name":"place1", "latitude":  "40.6",},
                      {"name": "place2", "latitude":  "-33.9",},
                      {"name": "place3", "latitude":  "-57.9"}],
  "earthRadius"    : 6371.0
}